# Generated by Django 5.2.7 on 2025-10-17 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Refugio',
            fields=[
                ('id_refugio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=150, null=True)),
                ('correo_contacto', models.EmailField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('direccion_completa', models.CharField(blank=True, max_length=255, null=True)),
                ('comuna', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=150, null=True)),
                ('tipo_usuario', models.CharField(choices=[('adoptante', 'Adoptante'), ('donante', 'Donante'), ('voluntario', 'Voluntario'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('contador_voluntariados', models.PositiveIntegerField(default=0)),
                ('contador_hogares_temporales', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id_animal', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('especie', models.CharField(max_length=50)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('adoptado', 'Adoptado'), ('en_hogar_temporal', 'En hogar temporal')], default='disponible', max_length=20)),
                ('busca_hogar_temporal', models.BooleanField(default=False)),
                ('motivo_hogar_temporal', models.TextField(blank=True, null=True)),
                ('duracion_estimada_hogar', models.CharField(blank=True, max_length=50, null=True)),
                ('refugio', models.ForeignKey(db_column='id_refugio', on_delete=django.db.models.deletion.CASCADE, related_name='animales', to='registry.refugio')),
            ],
        ),
    ]
