# Generated by Django 5.2.7 on 2025-10-24 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='motivo_cambio_hogar_temporal',
            field=models.TextField(blank=True, help_text='Motivo por el que el animal necesita cambiar de hogar temporal', null=True),
        ),
        migrations.AddField(
            model_name='hogarestemporales',
            name='region_hogar_temporal',
            field=models.CharField(blank=True, help_text='Región actual donde se encuentra el animal en hogar temporal', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hogarestemporales',
            name='regiones_postulacion',
            field=models.JSONField(blank=True, default=list, help_text='Lista de regiones donde el usuario acepta ser hogar temporal'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('adoptado', 'Adoptado'), ('en_hogar_temporal', 'En hogar temporal'), ('buscando_nuevo_hogar_temporal', 'Buscando nuevo hogar temporal')], default='disponible', max_length=30),
        ),
    ]
