# Generated by Django 5.2.7 on 2025-10-20 00:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoServicios',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(choices=[('vacuna', 'Vacuna'), ('desparasitacion', 'Desparasitación'), ('cirugia', 'Cirugía'), ('tratamiento', 'Tratamiento'), ('examen', 'Examen'), ('otro', 'Otro')], max_length=20)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('costo_promedio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('especie_aplicable', models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato'), ('ambos', 'Ambos')], max_length=10)),
                ('frecuencia', models.CharField(max_length=50)),
                ('es_obligatorio', models.BooleanField(default=False)),
                ('icono_url', models.CharField(blank=True, max_length=255, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Catálogo de Servicios',
                'db_table': 'catalogo_servicios',
            },
        ),
        migrations.CreateModel(
            name='Donaciones',
            fields=[
                ('id_donacion', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('unica', 'Única'), ('recurrente', 'Recurrente')], max_length=15)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completada', 'Completada'), ('fallida', 'Fallida')], default='pendiente', max_length=15)),
                ('transbank_token', models.CharField(blank=True, max_length=255, null=True)),
                ('id_refugio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.refugio')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Donaciones',
                'db_table': 'donaciones',
            },
        ),
        migrations.CreateModel(
            name='DonacionesEspecificas',
            fields=[
                ('id_donacion_especifica', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=1)),
                ('monto_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_uso', models.CharField(choices=[('pendiente', 'Pendiente'), ('utilizado', 'Utilizado'), ('parcial', 'Parcial')], default='pendiente', max_length=15)),
                ('fecha_uso', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('id_animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registry.animal')),
                ('id_donacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.donaciones')),
                ('id_refugio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.refugio')),
                ('id_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.catalogoservicios')),
            ],
            options={
                'verbose_name_plural': 'Donaciones Específicas',
                'db_table': 'donaciones_especificas',
            },
        ),
        migrations.CreateModel(
            name='ComprobantesServicio',
            fields=[
                ('id_comprobante', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(choices=[('foto_animal', 'Foto del Animal'), ('boleta', 'Boleta'), ('receta', 'Receta'), ('carnet_vacuna', 'Carnet de Vacuna'), ('otro', 'Otro')], max_length=20)),
                ('url_archivo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('verificado', models.BooleanField(default=False)),
                ('fecha_verificacion', models.DateTimeField(blank=True, null=True)),
                ('id_animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.animal')),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_donacion_especifica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.donacionesespecificas')),
            ],
            options={
                'verbose_name_plural': 'Comprobantes de Servicio',
                'db_table': 'comprobantes_servicio',
            },
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('lugar', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('id_refugio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.refugio')),
            ],
            options={
                'verbose_name_plural': 'Eventos',
                'db_table': 'eventos',
            },
        ),
        migrations.CreateModel(
            name='HistorialMedico',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_atencion', models.CharField(choices=[('vacuna', 'Vacuna'), ('desparasitacion', 'Desparasitación'), ('cirugia', 'Cirugía'), ('consulta', 'Consulta'), ('tratamiento', 'Tratamiento'), ('otro', 'Otro')], max_length=20)),
                ('descripcion', models.TextField()),
                ('veterinario', models.CharField(max_length=100)),
                ('clinica', models.CharField(max_length=150)),
                ('fecha', models.DateField()),
                ('proximo_control', models.DateField(blank=True, null=True)),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('documentos_url', models.CharField(blank=True, max_length=255, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('id_animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.animal')),
            ],
            options={
                'verbose_name_plural': 'Historiales Médicos',
                'db_table': 'historial_medico',
            },
        ),
        migrations.CreateModel(
            name='HogaresTemporales',
            fields=[
                ('id_hogar', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('en_proceso', 'En Proceso'), ('aprobado', 'Aprobado'), ('finalizado', 'Finalizado'), ('rechazado', 'Rechazado'), ('cancelado_usuario', 'Cancelado por Usuario')], default='en_proceso', max_length=20)),
                ('motivo_postulacion', models.TextField()),
                ('experiencia_previa', models.TextField()),
                ('tipo_vivienda', models.CharField(choices=[('casa', 'Casa'), ('departamento', 'Departamento'), ('otro', 'Otro')], max_length=15)),
                ('tiene_otras_mascotas', models.BooleanField()),
                ('duracion_disponible', models.CharField(max_length=50)),
                ('fecha_postulacion', models.DateTimeField(auto_now_add=True)),
                ('motivo_rechazo', models.TextField(blank=True, null=True)),
                ('motivo_cancelacion', models.TextField(blank=True, null=True)),
                ('fecha_cancelacion', models.DateTimeField(blank=True, null=True)),
                ('id_animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.animal')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Hogares Temporales',
                'db_table': 'hogares_temporales',
            },
        ),
        migrations.CreateModel(
            name='InscripcionesEventos',
            fields=[
                ('id_inscripcion', models.AutoField(primary_key=True, serialize=False)),
                ('asistencia', models.BooleanField(default=False)),
                ('id_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.eventos')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Inscripciones a Eventos',
                'db_table': 'inscripciones_eventos',
            },
        ),
        migrations.CreateModel(
            name='NecesidadesRefugio',
            fields=[
                ('id_necesidad', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('alimento', 'Alimento'), ('medicamento', 'Medicamento'), ('servicio', 'Servicio'), ('articulo', 'Artículo'), ('otro', 'Otro')], max_length=15)),
                ('descripcion', models.CharField(max_length=200)),
                ('monto_necesario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_recaudado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('cumplida', 'Cumplida'), ('cancelada', 'Cancelada')], default='activa', max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_limite', models.DateField(blank=True, null=True)),
                ('imagen_url', models.CharField(blank=True, max_length=255, null=True)),
                ('id_refugio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.refugio')),
            ],
            options={
                'verbose_name_plural': 'Necesidades de Refugio',
                'db_table': 'necesidades_refugio',
            },
        ),
        migrations.CreateModel(
            name='PerfilAdoptante',
            fields=[
                ('id_perfil', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_vivienda', models.CharField(choices=[('casa', 'Casa'), ('depto', 'Departamento')], max_length=10)),
                ('tiene_patio', models.BooleanField()),
                ('horas_disponibles', models.CharField(choices=[('muchas', 'Muchas'), ('algunas', 'Algunas'), ('pocas', 'Pocas')], max_length=10)),
                ('nivel_energia', models.CharField(choices=[('activo', 'Activo'), ('moderado', 'Moderado'), ('tranquilo', 'Tranquilo')], max_length=10)),
                ('tiene_mascotas', models.BooleanField()),
                ('tiene_ninos', models.BooleanField()),
                ('experiencia_previa', models.BooleanField()),
                ('id_usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Perfiles de Adoptantes',
                'db_table': 'perfil_adoptante',
            },
        ),
        migrations.CreateModel(
            name='Suscripciones',
            fields=[
                ('id_suscripcion', models.AutoField(primary_key=True, serialize=False)),
                ('monto_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('pausada', 'Pausada'), ('cancelada', 'Cancelada')], default='activa', max_length=15)),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('fecha_proximo_cobro', models.DateField()),
                ('id_refugio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.refugio')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Suscripciones',
                'db_table': 'suscripciones',
            },
        ),
    ]
