# Generated by Django 5.2.7 on 2025-11-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_animal_motivo_cambio_hogar_temporal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostulacionRefugio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('persona_contacto', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=200)),
                ('comuna', models.CharField(max_length=80)),
                ('region', models.CharField(choices=[('Arica y Parinacota', 'Arica y Parinacota'), ('Tarapacá', 'Tarapacá'), ('Antofagasta', 'Antofagasta'), ('Atacama', 'Atacama'), ('Coquimbo', 'Coquimbo'), ('Valparaíso', 'Valparaíso'), ('Metropolitana', 'Metropolitana'), ("O'Higgins", "O'Higgins"), ('Maule', 'Maule'), ('Ñuble', 'Ñuble'), ('Biobío', 'Biobío'), ('La Araucanía', 'La Araucanía'), ('Los Ríos', 'Los Ríos'), ('Los Lagos', 'Los Lagos'), ('Aysén', 'Aysén'), ('Magallanes', 'Magallanes')], max_length=80)),
                ('cantidad_animales', models.PositiveIntegerField(default=0)),
                ('tipos_animales', models.CharField(max_length=120)),
                ('descripcion', models.TextField()),
                ('ano_fundacion', models.CharField(blank=True, max_length=10)),
                ('sitios_web', models.JSONField(blank=True, default=list, help_text='Lista de enlaces y redes sociales del refugio')),
                ('personalidad_juridica', models.BooleanField(default=False)),
                ('organizaciones_previas', models.TextField(blank=True)),
                ('necesidades_actuales', models.TextField(blank=True)),
                ('estado', models.CharField(default='pendiente', max_length=20)),
                ('fecha_postulacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
