# Generated by Django 5.2.7 on 2025-11-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0004_alter_refugio_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='sexo',
            field=models.CharField(blank=True, choices=[('Macho', 'Macho'), ('Hembra', 'Hembra')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='tamano',
            field=models.CharField(blank=True, choices=[('Pequeño', 'Pequeño'), ('Pequeño-Grande', 'Pequeño-Grande'), ('Media', 'Media'), ('Mediano', 'Mediano'), ('Mediano-Grande', 'Mediano-Grande'), ('Grande', 'Grande'), ('Gigante', 'Gigante')], max_length=20, null=True),
        ),
    ]
