# Generated by Django 5.2.7 on 2025-11-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0005_animal_sexo_animal_tamano'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='vacunas',
            field=models.JSONField(blank=True, default=list, help_text='Lista de vacunas del animal'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='motivo_hogar_temporal',
            field=models.TextField(blank=True, help_text='Descripción si busca hogar temporal', null=True),
        ),
    ]
