# Generated by Django 5.2.7 on 2025-11-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0006_animal_vacunas_alter_animal_motivo_hogar_temporal'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='fotos',
            field=models.JSONField(blank=True, default=list, help_text='Lista de hasta 3 URLs de fotos del animal'),
        ),
    ]
