# Generated by Django 5.2.7 on 2025-11-02 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0007_animal_fotos'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='fecha_cumpleanos',
            field=models.DateField(blank=True, help_text='Fecha de cumpleaños del animal (opcional)', null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='fecha_ingreso',
            field=models.DateField(blank=True, help_text='Fecha de ingreso al refugio', null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='ubicacion_actual',
            field=models.CharField(choices=[('refugio', 'Refugio'), ('hogar_temporal', 'Hogar temporal')], default='refugio', help_text='Ubicación actual del animal', max_length=20),
        ),
    ]
