# Generated by Django 5.2.7 on 2025-11-03 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0008_animal_fecha_cumpleanos_animal_fecha_ingreso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulacionrefugio',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
