# Generated by Django 5.2.7 on 2025-11-04 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0009_postulacionrefugio_observaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cirugia',
            fields=[
                ('id_cirugia', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100)),
                ('otro_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('veterinario', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('pago_estado', models.CharField(choices=[('pagada', 'Pagada'), ('no_pagada', 'No pagada'), ('parcial', 'Parcialmente pagada')], default='no_pagada', max_length=15)),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('adjunto', models.FileField(blank=True, null=True, upload_to='cirugias_adjuntos/')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('id_animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cirugias', to='registry.animal')),
            ],
            options={
                'verbose_name_plural': 'Cirugías',
                'db_table': 'cirugias',
            },
        ),
    ]
