# Generated by Django 5.2.7 on 2025-11-04 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0010_cirugia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id_tratamiento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('duracion_dias', models.IntegerField(blank=True, null=True)),
                ('dosis', models.CharField(max_length=100)),
                ('via_administracion', models.CharField(max_length=50)),
                ('veterinario', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(choices=[('en_curso', 'En curso'), ('finalizado', 'Finalizado'), ('suspendido', 'Suspendido'), ('pendiente', 'Pendiente')], default='en_curso', max_length=15)),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pagado', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('adjunto', models.FileField(blank=True, null=True, upload_to='tratamientos_adjuntos/')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('id_animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tratamientos', to='registry.animal')),
            ],
            options={
                'verbose_name_plural': 'Tratamientos',
                'db_table': 'tratamientos',
            },
        ),
    ]
