# Generated by Django 5.2.7 on 2025-11-05 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0012_solicitudadopcion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'verbose_name_plural': 'Alergias y Condiciones Crónicas'},
        ),
        migrations.AlterModelTable(
            name='animal',
            table='alergia_condicion',
        ),
        migrations.CreateModel(
            name='AlergiaCondicion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('alergia', 'Alergia'), ('condicion_cronica', 'Condición Crónica')], max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alergias_condiciones', to='registry.animal')),
            ],
        ),
    ]
