# Generated by Django 5.2.7 on 2025-11-05 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0014_alergiacondicion_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alergiacondicion',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='alergiacondicion',
            name='fecha_diagnostico',
        ),
    ]
