# Generated by Django 5.2.7 on 2025-11-05 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0015_remove_alergiacondicion_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alergiacondicion',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alergiacondicion',
            name='fecha_diagnostico',
            field=models.DateField(blank=True, null=True),
        ),
    ]
