# Generated by Django 5.2.7 on 2025-11-05 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0016_alergiacondicion_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tratamiento',
            name='pagado',
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='estado_pago',
            field=models.CharField(choices=[('no_pagado', 'No pagado'), ('parcialmente_pagado', 'Parcialmente pagado'), ('pagado', 'Pagado')], default='no_pagado', max_length=22),
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='monto_pagado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
