# Generated by Django 5.2.7 on 2025-11-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0017_remove_tratamiento_pagado_tratamiento_estado_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refugio',
            name='ano_fundacion',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='refugio',
            name='estado',
            field=models.CharField(default='activo', max_length=20),
        ),
        migrations.AddField(
            model_name='refugio',
            name='horario_atencion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='refugio',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='refugios_logos/'),
        ),
        migrations.AddField(
            model_name='refugio',
            name='personalidad_juridica',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='refugio',
            name='redes_sociales',
            field=models.JSONField(blank=True, default=list, help_text='Lista de enlaces y redes sociales'),
        ),
        migrations.AddField(
            model_name='refugio',
            name='servicios_ofrecidos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refugio',
            name='sitio_web',
            field=models.URLField(blank=True, null=True),
        ),
    ]
