# Generated by Django 5.2.7 on 2025-11-05 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0018_refugio_ano_fundacion_refugio_estado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'verbose_name_plural': 'Animales'},
        ),
        migrations.AlterModelTable(
            name='animal',
            table='animal',
        ),
    ]
