# Generated by Django 5.2.7 on 2025-11-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0018_refugio_ano_fundacion_refugio_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refugio',
            name='banco',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='refugio',
            name='correo_donacion',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='refugio',
            name='nombre_titular',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='refugio',
            name='numero_cuenta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='refugio',
            name='rut_titular',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='refugio',
            name='tipo_cuenta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
