# Generated by Django 5.2.7 on 2025-11-05 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0019_refugio_banco_refugio_correo_donacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refugio',
            name='tipo_cuenta',
            field=models.CharField(blank=True, choices=[('Corriente', 'Cuenta Corriente'), ('Vista', 'Cuenta Vista'), ('Ahorro', 'Cuenta de Ahorro'), ('RUT', 'Cuenta RUT')], max_length=50, null=True),
        ),
    ]
