# Generated by Django 5.2.7 on 2025-11-05 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0019_alter_animal_options_alter_animal_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'verbose_name_plural': 'Alergias y Condiciones Crónicas'},
        ),
        migrations.AddField(
            model_name='animal',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='desparasitado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='animal',
            name='esterilizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelTable(
            name='animal',
            table='alergia_condicion',
        ),
    ]
