# Generated by Django 5.2.7 on 2025-11-05 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0020_alter_animal_options_animal_descripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaMedica',
            fields=[
                ('id_ficha', models.AutoField(primary_key=True, serialize=False)),
                ('estado_salud', models.CharField(choices=[('sano', 'Sano'), ('en_tratamiento', 'En tratamiento'), ('en_recuperacion', 'En recuperación'), ('condicion_cronica', 'Condición crónica')], default='sano', max_length=30)),
                ('peso_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fecha_ultimo_control', models.DateField(blank=True, null=True)),
                ('veterinario_responsable', models.CharField(blank=True, max_length=100, null=True)),
                ('clinica', models.CharField(blank=True, max_length=100, null=True)),
                ('recomendaciones', models.TextField(blank=True, null=True)),
                ('animal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha_medica', to='registry.animal')),
            ],
            options={
                'verbose_name_plural': 'Fichas médicas',
                'db_table': 'ficha_medica',
            },
        ),
    ]
