# Generated by Django 5.2.7 on 2025-11-06 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0022_delete_historialmedico'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'verbose_name_plural': 'Animales'},
        ),
        migrations.AddField(
            model_name='animal',
            name='tipo_edad',
            field=models.CharField(choices=[('anios', 'Años'), ('meses', 'Meses')], default='anios', max_length=10),
        ),
        migrations.AlterField(
            model_name='animal',
            name='edad',
            field=models.IntegerField(blank=True, help_text='Edad en años o meses según tipo_edad', null=True),
        ),
        migrations.AlterModelTable(
            name='animal',
            table='animales',
        ),
    ]
