# Generated by Django 5.2.7 on 2025-11-06 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0023_alter_animal_options_animal_tipo_edad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hogarestemporales',
            name='id_animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registry.animal'),
        ),
    ]
