# Generated by Django 5.2.7 on 2025-11-06 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0024_alter_hogarestemporales_id_animal'),
    ]

    operations = [
        migrations.AddField(
            model_name='hogarestemporales',
            name='comuna',
            field=models.CharField(blank=True, help_text='Comuna del hogar temporal', max_length=100, null=True),
        ),
    ]
