# Generated by Django 5.2.7 on 2025-11-07 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0025_hogarestemporales_comuna'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichamedica',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Notas adicionales del veterinario o del refugio', null=True),
        ),
    ]
