# Generated by Django 5.2.7 on 2025-11-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0027_alter_animal_tamano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='tamano',
            field=models.CharField(blank=True, choices=[('Pequeño', 'Pequeño'), ('Pequeño-Mediano', 'Pequeño-Mediano'), ('Mediano', 'Mediano'), ('Mediano-Grande', 'Mediano-Grande'), ('Grande', 'Grande'), ('Gigante', 'Gigante')], max_length=20, null=True),
        ),
    ]
