# Generated by Django 5.2.7 on 2025-11-08 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0028_alter_animal_tamano'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='vacunas',
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('unica', 'Única'), ('refuerzo', 'Refuerzo')], max_length=10)),
                ('fecha_aplicacion', models.DateField()),
                ('fecha_refuerzo', models.DateField(blank=True, help_text='Fecha de refuerzo si aplica', null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacunas', to='registry.animal')),
            ],
        ),
    ]
