# Generated by Django 5.2.8 on 2025-11-13 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0028_alter_animal_tamano'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventos',
            options={'ordering': ['fecha_hora_inicio'], 'verbose_name_plural': 'Eventos'},
        ),
        migrations.RemoveField(
            model_name='eventos',
            name='fecha',
        ),
        migrations.AddField(
            model_name='eventos',
            name='es_voluntariado',
            field=models.BooleanField(default=False, help_text='Marcar si este evento es principalmente una jornada de voluntariado.'),
        ),
        migrations.AddField(
            model_name='eventos',
            name='fecha_hora_fin',
            field=models.DateTimeField(default='2024-01-01 00:00', help_text='Fecha y hora de finalización del evento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventos',
            name='fecha_hora_inicio',
            field=models.DateTimeField(default='2024-01-01 00:00', help_text='Fecha y hora de inicio del evento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventos',
            name='requiere_inscripcion',
            field=models.BooleanField(default=False, help_text='Marcar si los usuarios deben inscribirse para asistir.'),
        ),
        migrations.AddField(
            model_name='inscripcioneseventos',
            name='fecha_inscripcion',
            field=models.DateTimeField(auto_now_add=True, default='2024-01-01 00:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventos',
            name='id_refugio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='registry.refugio'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='lugar',
            field=models.CharField(help_text='Dirección o lugar del evento', max_length=150),
        ),
        migrations.AlterField(
            model_name='inscripcioneseventos',
            name='id_evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='registry.eventos'),
        ),
        migrations.AlterField(
            model_name='inscripcioneseventos',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones_evento', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='inscripcioneseventos',
            unique_together={('id_usuario', 'id_evento')},
        ),
    ]
