# Generated by Django 5.2.8 on 2025-11-15 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0029_alter_eventos_options_remove_eventos_fecha_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='eventos_media/')),
                ('tipo', models.CharField(choices=[('foto', 'Foto'), ('video', 'Video')], default='foto', max_length=10)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Archivos de Evento',
                'db_table': 'archivos_evento',
            },
        ),
        migrations.AddField(
            model_name='eventos',
            name='archivos',
            field=models.ManyToManyField(blank=True, help_text='Archivos multimedia del evento (fotos/videos)', related_name='eventos', to='registry.archivoevento'),
        ),
    ]
