# Generated by Django 5.2.7 on 2025-11-08 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0029_remove_animal_vacunas_vacuna'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacuna',
            name='nombre',
            field=models.CharField(default='Sin nombre', help_text='Nombre de la vacuna', max_length=100),
        ),
    ]
