# Generated by Django 5.2.7 on 2025-11-08 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0030_vacuna_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='NecesidadRefugio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('alimento', 'Alimento'), ('medicamento', 'Medicamento'), ('servicio', 'Servicio'), ('articulo', 'Artículo'), ('otro', 'Otro')], max_length=20)),
                ('descripcion', models.TextField()),
                ('monto_necesario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monto_recaudado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('cumplida', 'Cumplida'), ('cancelada', 'Cancelada')], default='activa', max_length=10)),
                ('fecha_limite', models.DateField(blank=True, null=True)),
                ('imagen_url', models.URLField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('refugio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='necesidades', to='registry.refugio')),
            ],
        ),
    ]
