# Generated by Django 5.2.8 on 2025-11-15 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0020_alter_refugio_tipo_cuenta'),
        ('registry', '0031_necesidadrefugio'),
    ]

    operations = [
    ]
