# Generated by Django 5.2.8 on 2025-11-16 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0031_necesidadrefugio'),
    ]

    operations = [
        migrations.AddField(
            model_name='refugio',
            name='banco',
            field=models.CharField(blank=True, help_text='Banco del refugio para donaciones', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='refugio',
            name='numero_cuenta',
            field=models.CharField(blank=True, help_text='Número de cuenta bancaria', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='refugio',
            name='rut_titular',
            field=models.CharField(blank=True, help_text='RUT del titular de la cuenta', max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='refugio',
            name='tipo_cuenta',
            field=models.CharField(blank=True, help_text='Tipo de cuenta bancaria', max_length=50, null=True),
        ),
    ]
