# Generated by Django 5.2.7 on 2025-11-17 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0033_listavacunasanimal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
