# Generated by Django 5.2.7 on 2025-11-17 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0035_especies_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaVacunasEspecie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('frecuencia', models.CharField(blank=True, max_length=100)),
                ('dosis', models.CharField(blank=True, max_length=50)),
                ('obligatoria', models.BooleanField(default=False)),
                ('tipo', models.CharField(choices=[('unica', 'Única'), ('refuerzo', 'Refuerzo')], default='unica', max_length=20)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listas_vacunas', to='registry.especie')),
            ],
        ),
    ]
