# Generated by Django 5.2.7 on 2025-11-17 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0036_listavacunasespecie'),
    ]

    operations = [
        migrations.AddField(
            model_name='refugio',
            name='email_bancario',
            field=models.EmailField(blank=True, help_text='Correo asociado a la cuenta bancaria', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='refugio',
            name='titular_cuenta',
            field=models.CharField(blank=True, help_text='Nombre del titular de la cuenta bancaria', max_length=100, null=True),
        ),
    ]
