# Generated by Django 5.2.7 on 2025-11-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0037_refugio_email_bancario_refugio_titular_cuenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='donaciones',
            name='comprobante_imagen',
            field=models.ImageField(blank=True, help_text='Comprobante de transferencia (imagen)', null=True, upload_to='donaciones_comprobantes/'),
        ),
    ]
