# Generated by Django 5.2.7 on 2025-11-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0038_donaciones_comprobante_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='donacionesespecificas',
            name='comentario_donador',
            field=models.TextField(blank=True, help_text='Comentario del donador', null=True),
        ),
        migrations.AddField(
            model_name='donacionesespecificas',
            name='nombre_donador',
            field=models.CharField(blank=True, help_text='Nombre del donador', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='donacionesespecificas',
            name='nombre_vacuna',
            field=models.CharField(blank=True, help_text='Nombre de la vacuna donada', max_length=100, null=True),
        ),
    ]
