# Generated by Django 5.2.8 on 2025-11-17 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0039_donacionesespecificas_comentario_donador_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donacionesespecificas',
            name='id_donacion',
        ),
        migrations.AddField(
            model_name='donacionesespecificas',
            name='comprobante_imagen',
            field=models.ImageField(blank=True, help_text='Comprobante de transferencia (imagen)', null=True, upload_to='donaciones_comprobantes/'),
        ),
        migrations.DeleteModel(
            name='Donaciones',
        ),
    ]
