# Generated by Django 5.2.8 on 2025-11-17 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0040_remove_donacionesespecificas_id_donacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donacionesespecificas',
            name='comprobante_refugio_1',
            field=models.ImageField(blank=True, help_text='Comprobante de uso enviado por el refugio (1)', null=True, upload_to='donaciones_comprobantes/'),
        ),
        migrations.AddField(
            model_name='donacionesespecificas',
            name='comprobante_refugio_2',
            field=models.ImageField(blank=True, help_text='Comprobante de uso enviado por el refugio (2)', null=True, upload_to='donaciones_comprobantes/'),
        ),
    ]
