# Generated by Django 5.2.8 on 2025-11-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0041_donacionesespecificas_comprobante_refugio_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donacionesespecificas',
            name='estado_uso',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('utilizado', 'Utilizado'), ('parcial', 'Parcial'), ('descartado', 'Descartado')], default='pendiente', max_length=15),
        ),
    ]
