# Generated by Django 5.2.8 on 2025-11-17 20:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0042_alter_donacionesespecificas_estado_uso'),
    ]

    operations = [
        migrations.AddField(
            model_name='donacionesespecificas',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donacionesespecificas',
            name='estado_uso',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('utilizado', 'Utilizado'), ('parcial', 'Parcial'), ('descartado', 'Descartado'), ('aprobado', 'Aprobado'), ('en proceso', 'En Proceso')], default='pendiente', max_length=15),
        ),
    ]
