# Generated by Django 5.2.8 on 2025-11-18 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0043_donacionesespecificas_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donacionesespecificas',
            name='id_usuario',
            field=models.ForeignKey(blank=True, help_text='Usuario que realizó la donación', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
